package com.aslam.zeshan.emailocr.Util;

public class LangUtil {

    public String toSort(int i) {
        switch (i) {
            case 0:
                return "aft";
            case 1:
                return "ara";
            case 2:
                return "aze";
            case 3:
                return "bel";
            case 4:
                return "ben";
            case 5:
                return "bul";
            case 6:
                return "cat";
            case 7:
                return "ces";
            case 8:
                return "chi_sim";
            case 9:
                return "chi_tra";
            case 10:
                return "chr";
            case 11:
                return "dan_frak";
            case 12:
                return "dan";
            case 13:
                return "deu_frak";
            case 14:
                return "deu";
            case 15:
                return "ell";
            case 16:
                return "eng";
            case 17:
                return "enm";
            case 18:
                return "epo";
            case 19:
                return "equ";
            case 20:
                return "est";
            case 21:
                return "eus";
            case 22:
                return "fin";
            case 23:
                return "fra";
            case 24:
                return "frk";
            case 25:
                return "frm";
            case 26:
                return "glg";
            case 27:
                return "grc";
            case 28:
                return "heb";
            case 29:
                return "hin";
            case 30:
                return "hrv";
            case 31:
                return "hun";
            case 32:
                return "ind";
            case 33:
                return "isl";
            case 34:
                return "ita_old";
            case 35:
                return "ita";
            case 36:
                return "jpn";
            case 37:
                return "kan";
            case 38:
                return "kor";
            case 39:
                return "lav";
            case 40:
                return "lit";
            case 41:
                return "mal";
            case 42:
                return "mkd";
            case 43:
                return "mlt";
            case 44:
                return "msa";
            case 45:
                return "nld";
            case 46:
                return "nor";
            case 47:
                return "osd";
            case 48:
                return "pol";
            case 49:
                return "por";
            case 50:
                return "ron";
            case 51:
                return "rus";
            case 52:
                return "rus+eng";
            case 53:
                return "slk_frank";
            case 54:
                return "slk";
            case 55:
                return "slv";
            case 56:
                return "spa_old";
            case 57:
                return "spa";
            case 58:
                return "sqi";
            case 59:
                return "srp";
            case 60:
                return "swa";
            case 61:
                return "swe";
            case 62:
                return "tam";
            case 63:
                return "tel";
            case 64:
                return "tgl";
            case 65:
                return "tha";
            case 66:
                return "tur";
            case 67:
                return "ukr";
            case 68:
                return "ukr+eng";
            case 69:
                return "vie";
        }
        return null;
    }
}
